name: Validate Dependabot file

on: 
  workflow_call:
    inputs:
      package-ecosystem:
        required: true
        type: string
      package-filename:
        required: true
        type: string

jobs:
  dependabot-validate:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: Check Dependabot paths
        shell: bash
        run: |
          for path in $(find . -name "${{ inputs.package-filename }}"); do
            path=${path#"."}
            path=${path%"/${{ inputs.package-filename }}"}
            if [ -z $path ]; then
              path="/"
            fi
            result=$(yq e '.updates.[] | select(.package-ecosystem == "${{ inputs.package-ecosystem }}" and .directory == "'${path}'") | .directory' .github/dependabot.yml)
            if [ -z $result ]; then
              echo "Dependabot entry not found for ${{ inputs.package-filename }} at ${path}"
              exit 1
            fi  
          done               
